/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Auth
 */
export interface Auth {
    /**
     * The authentication token
     * @type {string}
     * @memberof Auth
     */
    token: string;
}

/**
 * Check if a given object implements the Auth interface.
 */
export function instanceOfAuth(value: object): value is Auth {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthFromJSON(json: any): Auth {
    return AuthFromJSONTyped(json, false);
}

export function AuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): Auth {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function AuthToJSON(value?: Auth | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

