/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BackupType = {
    Archive: 'archive'
} as const;
export type BackupType = typeof BackupType[keyof typeof BackupType];


export function instanceOfBackupType(value: any): boolean {
    for (const key in BackupType) {
        if (Object.prototype.hasOwnProperty.call(BackupType, key)) {
            if ((BackupType as Record<string, BackupType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BackupTypeFromJSON(json: any): BackupType {
    return BackupTypeFromJSONTyped(json, false);
}

export function BackupTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupType {
    return json as BackupType;
}

export function BackupTypeToJSON(value?: BackupType | null): any {
    return value as any;
}

