/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackupDownload
 */
export interface BackupDownload {
    /**
     * The url where the file is available
     * @type {string}
     * @memberof BackupDownload
     */
    url: string;
    /**
     * After this date the link is no longer valid
     * @type {Date}
     * @memberof BackupDownload
     */
    validUntil: Date;
}

/**
 * Check if a given object implements the BackupDownload interface.
 */
export function instanceOfBackupDownload(value: object): value is BackupDownload {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('validUntil' in value) || value['validUntil'] === undefined) return false;
    return true;
}

export function BackupDownloadFromJSON(json: any): BackupDownload {
    return BackupDownloadFromJSONTyped(json, false);
}

export function BackupDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupDownload {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'validUntil': (new Date(json['validUntil'])),
    };
}

export function BackupDownloadToJSON(value?: BackupDownload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'validUntil': ((value['validUntil']).toISOString()),
    };
}

