/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperatingSystem } from './operating-system';
import {
    OperatingSystemFromJSON,
    OperatingSystemFromJSONTyped,
    OperatingSystemToJSON,
} from './operating-system';
import type { ConfigTemplate } from './config-template';
import {
    ConfigTemplateFromJSON,
    ConfigTemplateFromJSONTyped,
    ConfigTemplateToJSON,
} from './config-template';
import type { BinaryType } from './binary-type';
import {
    BinaryTypeFromJSON,
    BinaryTypeFromJSONTyped,
    BinaryTypeToJSON,
} from './binary-type';
import type { ZipFile } from './zip-file';
import {
    ZipFileFromJSON,
    ZipFileFromJSONTyped,
    ZipFileToJSON,
} from './zip-file';
import type { Steam } from './steam';
import {
    SteamFromJSON,
    SteamFromJSONTyped,
    SteamToJSON,
} from './steam';
import type { DockerImage } from './docker-image';
import {
    DockerImageFromJSON,
    DockerImageFromJSONTyped,
    DockerImageToJSON,
} from './docker-image';
import type { DockerCompose } from './docker-compose';
import {
    DockerComposeFromJSON,
    DockerComposeFromJSONTyped,
    DockerComposeToJSON,
} from './docker-compose';

/**
 * 
 * @export
 * @interface Binary
 */
export interface Binary {
    /**
     * The id of the binary
     * @type {number}
     * @memberof Binary
     */
    id: number;
    /**
     * The app id of the binary
     * @type {number}
     * @memberof Binary
     */
    appId: number;
    /**
     * The app id of the binary
     * @type {string}
     * @memberof Binary
     */
    name: string;
    /**
     * The version of the binary
     * @type {string}
     * @memberof Binary
     */
    version: string;
    /**
     * The type of the binary
     * @type {BinaryType}
     * @memberof Binary
     */
    type: BinaryType;
    /**
     * The operating system of the binary
     * @type {OperatingSystem}
     * @memberof Binary
     */
    os: OperatingSystem;
    /**
     * Indicates whether the binary is ready for use.
     * @type {boolean}
     * @memberof Binary
     */
    ready: boolean;
    /**
     * The config templates of the binary
     * @type {Array<ConfigTemplate>}
     * @memberof Binary
     */
    configTemplates?: Array<ConfigTemplate>;
    /**
     * The docker image of the binary
     * @type {DockerImage}
     * @memberof Binary
     */
    dockerImage?: DockerImage;
    /**
     * The docker compose file of the binary
     * @type {DockerCompose}
     * @memberof Binary
     */
    dockerCompose?: DockerCompose;
    /**
     * The ZIP file of the binary
     * @type {ZipFile}
     * @memberof Binary
     */
    zipFile?: ZipFile;
    /**
     * The steam of the binary
     * @type {Steam}
     * @memberof Binary
     */
    steam?: Steam;
}

/**
 * Check if a given object implements the Binary interface.
 */
export function instanceOfBinary(value: object): value is Binary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('os' in value) || value['os'] === undefined) return false;
    if (!('ready' in value) || value['ready'] === undefined) return false;
    return true;
}

export function BinaryFromJSON(json: any): Binary {
    return BinaryFromJSONTyped(json, false);
}

export function BinaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Binary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appId': json['appId'],
        'name': json['name'],
        'version': json['version'],
        'type': BinaryTypeFromJSON(json['type']),
        'os': OperatingSystemFromJSON(json['os']),
        'ready': json['ready'],
        'configTemplates': json['configTemplates'] == null ? undefined : ((json['configTemplates'] as Array<any>).map(ConfigTemplateFromJSON)),
        'dockerImage': json['dockerImage'] == null ? undefined : DockerImageFromJSON(json['dockerImage']),
        'dockerCompose': json['dockerCompose'] == null ? undefined : DockerComposeFromJSON(json['dockerCompose']),
        'zipFile': json['zipFile'] == null ? undefined : ZipFileFromJSON(json['zipFile']),
        'steam': json['steam'] == null ? undefined : SteamFromJSON(json['steam']),
    };
}

export function BinaryToJSON(value?: Binary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'appId': value['appId'],
        'name': value['name'],
        'version': value['version'],
        'type': BinaryTypeToJSON(value['type']),
        'os': OperatingSystemToJSON(value['os']),
        'ready': value['ready'],
        'configTemplates': value['configTemplates'] == null ? undefined : ((value['configTemplates'] as Array<any>).map(ConfigTemplateToJSON)),
        'dockerImage': DockerImageToJSON(value['dockerImage']),
        'dockerCompose': DockerComposeToJSON(value['dockerCompose']),
        'zipFile': ZipFileToJSON(value['zipFile']),
        'steam': SteamToJSON(value['steam']),
    };
}

