/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BinaryType = {
    ZipFile: 'zipFile',
    DockerImage: 'dockerImage',
    DockerCompose: 'dockerCompose',
    Steam: 'steam'
} as const;
export type BinaryType = typeof BinaryType[keyof typeof BinaryType];


export function instanceOfBinaryType(value: any): boolean {
    for (const key in BinaryType) {
        if (Object.prototype.hasOwnProperty.call(BinaryType, key)) {
            if ((BinaryType as Record<string, BinaryType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BinaryTypeFromJSON(json: any): BinaryType {
    return BinaryTypeFromJSONTyped(json, false);
}

export function BinaryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryType {
    return json as BinaryType;
}

export function BinaryTypeToJSON(value?: BinaryType | null): any {
    return value as any;
}

