/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigFile
 */
export interface ConfigFile {
    /**
     * The path in the container
     * @type {string}
     * @memberof ConfigFile
     */
    target: string;
    /**
     * The content of the config file
     * @type {string}
     * @memberof ConfigFile
     */
    content: string;
}

/**
 * Check if a given object implements the ConfigFile interface.
 */
export function instanceOfConfigFile(value: object): value is ConfigFile {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ConfigFileFromJSON(json: any): ConfigFile {
    return ConfigFileFromJSONTyped(json, false);
}

export function ConfigFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigFile {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'],
        'content': json['content'],
    };
}

export function ConfigFileToJSON(value?: ConfigFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'target': value['target'],
        'content': value['content'],
    };
}

