/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Constraints
 */
export interface Constraints {
    /**
     * The country where the server should be placed - it defines a region as a fallback if no free resources are available in the city
     * @type {string}
     * @memberof Constraints
     */
    country: string;
    /**
     * The city where the server should be placed
     * @type {string}
     * @memberof Constraints
     */
    city: string;
}

/**
 * Check if a given object implements the Constraints interface.
 */
export function instanceOfConstraints(value: object): value is Constraints {
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    return true;
}

export function ConstraintsFromJSON(json: any): Constraints {
    return ConstraintsFromJSONTyped(json, false);
}

export function ConstraintsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Constraints {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'],
        'city': json['city'],
    };
}

export function ConstraintsToJSON(value?: Constraints | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'country': value['country'],
        'city': value['city'],
    };
}

