/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBackupRequest
 */
export interface CreateBackupRequest {
    /**
     * The name of the backup
     * @type {string}
     * @memberof CreateBackupRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateBackupRequest interface.
 */
export function instanceOfCreateBackupRequest(value: object): value is CreateBackupRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateBackupRequestFromJSON(json: any): CreateBackupRequest {
    return CreateBackupRequestFromJSONTyped(json, false);
}

export function CreateBackupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBackupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateBackupRequestToJSON(value?: CreateBackupRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

