/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DockerRegistryType = {
    Dockerhub: 'dockerhub',
    Github: 'github',
    Gitlab: 'gitlab',
    Awsecr: 'awsecr',
    Azure: 'azure',
    Custom: 'custom',
    Default: 'default',
    Proget: 'proget',
    Quay: 'quay'
} as const;
export type DockerRegistryType = typeof DockerRegistryType[keyof typeof DockerRegistryType];


export function instanceOfDockerRegistryType(value: any): boolean {
    for (const key in DockerRegistryType) {
        if (Object.prototype.hasOwnProperty.call(DockerRegistryType, key)) {
            if ((DockerRegistryType as Record<string, DockerRegistryType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DockerRegistryTypeFromJSON(json: any): DockerRegistryType {
    return DockerRegistryTypeFromJSONTyped(json, false);
}

export function DockerRegistryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerRegistryType {
    return json as DockerRegistryType;
}

export function DockerRegistryTypeToJSON(value?: DockerRegistryType | null): any {
    return value as any;
}

