/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DockerTaskStatus
 */
export interface DockerTaskStatus {
    /**
     * The state of the task
     * @type {string}
     * @memberof DockerTaskStatus
     */
    state: string;
    /**
     * The message from the task
     * @type {string}
     * @memberof DockerTaskStatus
     */
    message: string;
    /**
     * The error from the task
     * @type {string}
     * @memberof DockerTaskStatus
     */
    err: string | null;
    /**
     * The timestamp of the status request
     * @type {string}
     * @memberof DockerTaskStatus
     */
    timestamp: string;
}

/**
 * Check if a given object implements the DockerTaskStatus interface.
 */
export function instanceOfDockerTaskStatus(value: object): value is DockerTaskStatus {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('err' in value) || value['err'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function DockerTaskStatusFromJSON(json: any): DockerTaskStatus {
    return DockerTaskStatusFromJSONTyped(json, false);
}

export function DockerTaskStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerTaskStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
        'message': json['message'],
        'err': json['err'],
        'timestamp': json['timestamp'],
    };
}

export function DockerTaskStatusToJSON(value?: DockerTaskStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'state': value['state'],
        'message': value['message'],
        'err': value['err'],
        'timestamp': value['timestamp'],
    };
}

