/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnvironmentVariable
 */
export interface EnvironmentVariable {
    /**
     * The key of the environment variable
     * @type {string}
     * @memberof EnvironmentVariable
     */
    key: string;
    /**
     * The value of the environment variable
     * @type {string}
     * @memberof EnvironmentVariable
     */
    value: string | null;
}

/**
 * Check if a given object implements the EnvironmentVariable interface.
 */
export function instanceOfEnvironmentVariable(value: object): value is EnvironmentVariable {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EnvironmentVariableFromJSON(json: any): EnvironmentVariable {
    return EnvironmentVariableFromJSONTyped(json, false);
}

export function EnvironmentVariableFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentVariable {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function EnvironmentVariableToJSON(value?: EnvironmentVariable | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

