/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EnvironmentVariableType = {
    Static: 'static',
    System: 'system',
    Port: 'port'
} as const;
export type EnvironmentVariableType = typeof EnvironmentVariableType[keyof typeof EnvironmentVariableType];


export function instanceOfEnvironmentVariableType(value: any): boolean {
    for (const key in EnvironmentVariableType) {
        if (Object.prototype.hasOwnProperty.call(EnvironmentVariableType, key)) {
            if ((EnvironmentVariableType as Record<string, EnvironmentVariableType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EnvironmentVariableTypeFromJSON(json: any): EnvironmentVariableType {
    return EnvironmentVariableTypeFromJSONTyped(json, false);
}

export function EnvironmentVariableTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentVariableType {
    return json as EnvironmentVariableType;
}

export function EnvironmentVariableTypeToJSON(value?: EnvironmentVariableType | null): any {
    return value as any;
}

