/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAuthTokenRequest
 */
export interface GetAuthTokenRequest {
    /**
     * The email of the user
     * @type {string}
     * @memberof GetAuthTokenRequest
     */
    email: string;
    /**
     * The password of the user
     * @type {string}
     * @memberof GetAuthTokenRequest
     */
    password: string;
    /**
     * The fusion session id of the user
     * @type {string}
     * @memberof GetAuthTokenRequest
     */
    sid: string;
}

/**
 * Check if a given object implements the GetAuthTokenRequest interface.
 */
export function instanceOfGetAuthTokenRequest(value: object): value is GetAuthTokenRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('sid' in value) || value['sid'] === undefined) return false;
    return true;
}

export function GetAuthTokenRequestFromJSON(json: any): GetAuthTokenRequest {
    return GetAuthTokenRequestFromJSONTyped(json, false);
}

export function GetAuthTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAuthTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'sid': json['sid'],
    };
}

export function GetAuthTokenRequestToJSON(value?: GetAuthTokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
        'sid': value['sid'],
    };
}

