/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OperatingSystem = {
    Windows: 'windows',
    Linux: 'linux'
} as const;
export type OperatingSystem = typeof OperatingSystem[keyof typeof OperatingSystem];


export function instanceOfOperatingSystem(value: any): boolean {
    for (const key in OperatingSystem) {
        if (Object.prototype.hasOwnProperty.call(OperatingSystem, key)) {
            if ((OperatingSystem as Record<string, OperatingSystem>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OperatingSystemFromJSON(json: any): OperatingSystem {
    return OperatingSystemFromJSONTyped(json, false);
}

export function OperatingSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatingSystem {
    return json as OperatingSystem;
}

export function OperatingSystemToJSON(value?: OperatingSystem | null): any {
    return value as any;
}

