/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Constraints } from './constraints';
import {
    ConstraintsFromJSON,
    ConstraintsFromJSONTyped,
    ConstraintsToJSON,
} from './constraints';

/**
 * 
 * @export
 * @interface Placement
 */
export interface Placement {
    /**
     * The constraints to use
     * @type {Constraints}
     * @memberof Placement
     */
    constraints: Constraints;
}

/**
 * Check if a given object implements the Placement interface.
 */
export function instanceOfPlacement(value: object): value is Placement {
    if (!('constraints' in value) || value['constraints'] === undefined) return false;
    return true;
}

export function PlacementFromJSON(json: any): Placement {
    return PlacementFromJSONTyped(json, false);
}

export function PlacementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Placement {
    if (json == null) {
        return json;
    }
    return {
        
        'constraints': ConstraintsFromJSON(json['constraints']),
    };
}

export function PlacementToJSON(value?: Placement | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'constraints': ConstraintsToJSON(value['constraints']),
    };
}

