/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Protocol = {
    Tcp: 'tcp',
    Udp: 'udp'
} as const;
export type Protocol = typeof Protocol[keyof typeof Protocol];


export function instanceOfProtocol(value: any): boolean {
    for (const key in Protocol) {
        if (Object.prototype.hasOwnProperty.call(Protocol, key)) {
            if ((Protocol as Record<string, Protocol>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProtocolFromJSON(json: any): Protocol {
    return ProtocolFromJSONTyped(json, false);
}

export function ProtocolFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protocol {
    return json as Protocol;
}

export function ProtocolToJSON(value?: Protocol | null): any {
    return value as any;
}

