/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PublishMode = {
    Host: 'host',
    Ingress: 'ingress'
} as const;
export type PublishMode = typeof PublishMode[keyof typeof PublishMode];


export function instanceOfPublishMode(value: any): boolean {
    for (const key in PublishMode) {
        if (Object.prototype.hasOwnProperty.call(PublishMode, key)) {
            if ((PublishMode as Record<string, PublishMode>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PublishModeFromJSON(json: any): PublishMode {
    return PublishModeFromJSONTyped(json, false);
}

export function PublishModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishMode {
    return json as PublishMode;
}

export function PublishModeToJSON(value?: PublishMode | null): any {
    return value as any;
}

