/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Resources
 */
export interface Resources {
    /**
     * The amount of cpu to allocate in cores
     * @type {number}
     * @memberof Resources
     */
    cpu: number;
    /**
     * The amount of memory to allocate in GB
     * @type {number}
     * @memberof Resources
     */
    memory: number;
}

/**
 * Check if a given object implements the Resources interface.
 */
export function instanceOfResources(value: object): value is Resources {
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    return true;
}

export function ResourcesFromJSON(json: any): Resources {
    return ResourcesFromJSONTyped(json, false);
}

export function ResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resources {
    if (json == null) {
        return json;
    }
    return {
        
        'cpu': json['cpu'],
        'memory': json['memory'],
    };
}

export function ResourcesToJSON(value?: Resources | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cpu': value['cpu'],
        'memory': value['memory'],
    };
}

