/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RestartPolicyCondition = {
    None: 'none',
    Any: 'any',
    OnFailure: 'on-failure'
} as const;
export type RestartPolicyCondition = typeof RestartPolicyCondition[keyof typeof RestartPolicyCondition];


export function instanceOfRestartPolicyCondition(value: any): boolean {
    for (const key in RestartPolicyCondition) {
        if (Object.prototype.hasOwnProperty.call(RestartPolicyCondition, key)) {
            if ((RestartPolicyCondition as Record<string, RestartPolicyCondition>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RestartPolicyConditionFromJSON(json: any): RestartPolicyCondition {
    return RestartPolicyConditionFromJSONTyped(json, false);
}

export function RestartPolicyConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestartPolicyCondition {
    return json as RestartPolicyCondition;
}

export function RestartPolicyConditionToJSON(value?: RestartPolicyCondition | null): any {
    return value as any;
}

