/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestartPolicyCondition } from './restart-policy-condition';
import {
    RestartPolicyConditionFromJSON,
    RestartPolicyConditionFromJSONTyped,
    RestartPolicyConditionToJSON,
} from './restart-policy-condition';

/**
 * 
 * @export
 * @interface RestartPolicy
 */
export interface RestartPolicy {
    /**
     * The condition for a restart
     * @type {RestartPolicyCondition}
     * @memberof RestartPolicy
     */
    condition: RestartPolicyCondition;
}

/**
 * Check if a given object implements the RestartPolicy interface.
 */
export function instanceOfRestartPolicy(value: object): value is RestartPolicy {
    if (!('condition' in value) || value['condition'] === undefined) return false;
    return true;
}

export function RestartPolicyFromJSON(json: any): RestartPolicy {
    return RestartPolicyFromJSONTyped(json, false);
}

export function RestartPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestartPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'condition': RestartPolicyConditionFromJSON(json['condition']),
    };
}

export function RestartPolicyToJSON(value?: RestartPolicy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'condition': RestartPolicyConditionToJSON(value['condition']),
    };
}

