/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecretFile
 */
export interface SecretFile {
    /**
     * The path in the container
     * @type {string}
     * @memberof SecretFile
     */
    target: string;
    /**
     * The content of the secret file
     * @type {string}
     * @memberof SecretFile
     */
    content: string;
}

/**
 * Check if a given object implements the SecretFile interface.
 */
export function instanceOfSecretFile(value: object): value is SecretFile {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SecretFileFromJSON(json: any): SecretFile {
    return SecretFileFromJSONTyped(json, false);
}

export function SecretFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretFile {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'],
        'content': json['content'],
    };
}

export function SecretFileToJSON(value?: SecretFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'target': value['target'],
        'content': value['content'],
    };
}

