/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceLogs
 */
export interface ServiceLogs {
    /**
     * The logs as a string with newlines
     * @type {string}
     * @memberof ServiceLogs
     */
    logs: string;
}

/**
 * Check if a given object implements the ServiceLogs interface.
 */
export function instanceOfServiceLogs(value: object): value is ServiceLogs {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    return true;
}

export function ServiceLogsFromJSON(json: any): ServiceLogs {
    return ServiceLogsFromJSONTyped(json, false);
}

export function ServiceLogsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceLogs {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'],
    };
}

export function ServiceLogsToJSON(value?: ServiceLogs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'logs': value['logs'],
    };
}

