/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Steam
 */
export interface Steam {
    /**
     * The Steam App ID
     * @type {number}
     * @memberof Steam
     */
    steamAppId: number;
    /**
     * The branch to use
     * @type {string}
     * @memberof Steam
     */
    branch: string;
    /**
     * The password to use
     * @type {string}
     * @memberof Steam
     */
    password: string | null;
}

/**
 * Check if a given object implements the Steam interface.
 */
export function instanceOfSteam(value: object): value is Steam {
    if (!('steamAppId' in value) || value['steamAppId'] === undefined) return false;
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SteamFromJSON(json: any): Steam {
    return SteamFromJSONTyped(json, false);
}

export function SteamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Steam {
    if (json == null) {
        return json;
    }
    return {
        
        'steamAppId': json['steamAppId'],
        'branch': json['branch'],
        'password': json['password'],
    };
}

export function SteamToJSON(value?: Steam | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'steamAppId': value['steamAppId'],
        'branch': value['branch'],
        'password': value['password'],
    };
}

