/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Placement } from './placement';
import {
    PlacementFromJSON,
    PlacementFromJSONTyped,
    PlacementToJSON,
} from './placement';

/**
 * 
 * @export
 * @interface UpdateAppLocationSettingRequest
 */
export interface UpdateAppLocationSettingRequest {
    /**
     * The name of the location setting
     * @type {string}
     * @memberof UpdateAppLocationSettingRequest
     */
    name: string;
    /**
     * The id of the server configuration that should be deployed
     * @type {number}
     * @memberof UpdateAppLocationSettingRequest
     */
    serverConfigId: number;
    /**
     * Whether auto scaler is enabled
     * @type {boolean}
     * @memberof UpdateAppLocationSettingRequest
     */
    autoScalerEnabled: boolean;
    /**
     * The minimum number of instances that should run at the specific location
     * @type {number}
     * @memberof UpdateAppLocationSettingRequest
     */
    autoScalerMin?: number;
    /**
     * The maximum number of instances that should run at the specific location
     * @type {number}
     * @memberof UpdateAppLocationSettingRequest
     */
    autoScalerMax?: number;
    /**
     * The number of instances that should run at the specific location
     * @type {number}
     * @memberof UpdateAppLocationSettingRequest
     */
    numInstances: number;
    /**
     * The placement settings that define the location and other constraints
     * @type {Placement}
     * @memberof UpdateAppLocationSettingRequest
     */
    placement?: Placement;
}

/**
 * Check if a given object implements the UpdateAppLocationSettingRequest interface.
 */
export function instanceOfUpdateAppLocationSettingRequest(value: object): value is UpdateAppLocationSettingRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('serverConfigId' in value) || value['serverConfigId'] === undefined) return false;
    if (!('autoScalerEnabled' in value) || value['autoScalerEnabled'] === undefined) return false;
    if (!('numInstances' in value) || value['numInstances'] === undefined) return false;
    return true;
}

export function UpdateAppLocationSettingRequestFromJSON(json: any): UpdateAppLocationSettingRequest {
    return UpdateAppLocationSettingRequestFromJSONTyped(json, false);
}

export function UpdateAppLocationSettingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAppLocationSettingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'serverConfigId': json['serverConfigId'],
        'autoScalerEnabled': json['autoScalerEnabled'],
        'autoScalerMin': json['autoScalerMin'] == null ? undefined : json['autoScalerMin'],
        'autoScalerMax': json['autoScalerMax'] == null ? undefined : json['autoScalerMax'],
        'numInstances': json['numInstances'],
        'placement': json['placement'] == null ? undefined : PlacementFromJSON(json['placement']),
    };
}

export function UpdateAppLocationSettingRequestToJSON(value?: UpdateAppLocationSettingRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'serverConfigId': value['serverConfigId'],
        'autoScalerEnabled': value['autoScalerEnabled'],
        'autoScalerMin': value['autoScalerMin'],
        'autoScalerMax': value['autoScalerMax'],
        'numInstances': value['numInstances'],
        'placement': PlacementToJSON(value['placement']),
    };
}

