/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZipFile
 */
export interface ZipFile {
    /**
     * The URL to the ZIP file
     * @type {string}
     * @memberof ZipFile
     */
    zipFileUrl: string;
    /**
     * The command line to use
     * @type {string}
     * @memberof ZipFile
     */
    commandLine: string;
}

/**
 * Check if a given object implements the ZipFile interface.
 */
export function instanceOfZipFile(value: object): value is ZipFile {
    if (!('zipFileUrl' in value) || value['zipFileUrl'] === undefined) return false;
    if (!('commandLine' in value) || value['commandLine'] === undefined) return false;
    return true;
}

export function ZipFileFromJSON(json: any): ZipFile {
    return ZipFileFromJSONTyped(json, false);
}

export function ZipFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZipFile {
    if (json == null) {
        return json;
    }
    return {
        
        'zipFileUrl': json['zipFileUrl'],
        'commandLine': json['commandLine'],
    };
}

export function ZipFileToJSON(value?: ZipFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'zipFileUrl': value['zipFileUrl'],
        'commandLine': value['commandLine'],
    };
}

